"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sudo.types import BaseModel
from typing_extensions import TypedDict


class ChatDeletionConfirmationTypedDict(TypedDict):
    deleted: bool
    id: str
    object: str


class ChatDeletionConfirmation(BaseModel):
    deleted: bool

    id: str

    object: str
