"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from sudo.types import BaseModel
from typing_extensions import TypedDict


class SupportedModelTypedDict(TypedDict):
    created_at: datetime
    model_name: str
    model_provider: str
    sudo_model_id: int


class SupportedModel(BaseModel):
    created_at: datetime

    model_name: str

    model_provider: str

    sudo_model_id: int
