"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolcallfunction import ToolCallFunction, ToolCallFunctionTypedDict
from sudo.types import BaseModel
from typing_extensions import TypedDict


class ToolCallTypedDict(TypedDict):
    function: ToolCallFunctionTypedDict
    id: str
    type: str


class ToolCall(BaseModel):
    function: ToolCallFunction

    id: str

    type: str
