"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .function import Function, FunctionTypedDict
from sudo.types import BaseModel
from typing_extensions import TypedDict


class ToolTypedDict(TypedDict):
    function: FunctionTypedDict
    type: str


class Tool(BaseModel):
    function: Function

    type: str
