"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sudo_ai.errors import SudoError
from sudo_ai.models import errordetail as models_errordetail
from sudo_ai.types import BaseModel
from typing import Optional


class ErrorResponseData(BaseModel):
    error: models_errordetail.ErrorDetail


class ErrorResponse(SudoError):
    data: ErrorResponseData

    def __init__(
        self,
        data: ErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
