workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    sudo-api:
        inputs:
            - location: openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/committee-services/default/sudo-api
targets:
    sudo:
        target: python
        source: sudo-api
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/committee-services/default/sudo-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
