"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .returnedchatmessages import ReturnedChatMessages, ReturnedChatMessagesTypedDict
from sudo_ai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ChatMessageListTypedDict(TypedDict):
    data: List[ReturnedChatMessagesTypedDict]
    first_id: str
    has_more: bool
    last_id: str
    object: str


class ChatMessageList(BaseModel):
    data: List[ReturnedChatMessages]

    first_id: str

    has_more: bool

    last_id: str

    object: str
