"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletion import ChatCompletion, ChatCompletionTypedDict
from sudo_ai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ChatCompletionListTypedDict(TypedDict):
    data: List[ChatCompletionTypedDict]
    first_id: str
    has_more: bool
    last_id: str
    object: str


class ChatCompletionList(BaseModel):
    data: List[ChatCompletion]

    first_id: str

    has_more: bool

    last_id: str

    object: str
