"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messageresponse import MessageResponse, MessageResponseTypedDict
from sudo_ai.types import BaseModel
from typing import Any, Optional
from typing_extensions import NotRequired, TypedDict


class ChoiceTypedDict(TypedDict):
    finish_reason: str
    index: int
    message: MessageResponseTypedDict
    logprobs: NotRequired[Any]


class Choice(BaseModel):
    finish_reason: str

    index: int

    message: MessageResponse

    logprobs: Optional[Any] = None
