"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sudo_ai.types import BaseModel
from sudo_ai.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetChatCompletionRequestTypedDict(TypedDict):
    completion_id: str
    r"""ID of the chat completion"""


class GetChatCompletionRequest(BaseModel):
    completion_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the chat completion"""
