"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imageinputtokens import ImageInputTokens, ImageInputTokensTypedDict
from sudo_ai.types import BaseModel
from typing_extensions import TypedDict


class ImageUsageTypedDict(TypedDict):
    input_tokens: int
    r"""Number of tokens in the input prompt."""
    input_tokens_details: ImageInputTokensTypedDict
    output_tokens: int
    r"""Number of tokens used for the generated image."""
    total_tokens: int
    r"""Total number of tokens used in the request (input + output)."""


class ImageUsage(BaseModel):
    input_tokens: int
    r"""Number of tokens in the input prompt."""

    input_tokens_details: ImageInputTokens

    output_tokens: int
    r"""Number of tokens used for the generated image."""

    total_tokens: int
    r"""Total number of tokens used in the request (input + output)."""
