"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sudo_ai.types import BaseModel
from typing_extensions import TypedDict


class ImageInputTokensTypedDict(TypedDict):
    image_tokens: int
    r"""Number of tokens used for image processing."""
    text_tokens: int
    r"""Number of tokens used for text processing."""


class ImageInputTokens(BaseModel):
    image_tokens: int
    r"""Number of tokens used for image processing."""

    text_tokens: int
    r"""Number of tokens used for text processing."""
