"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contentpart_union import ContentPartUnion, ContentPartUnionTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


MessageContentTypedDict = TypeAliasType(
    "MessageContentTypedDict", Union[str, List[ContentPartUnionTypedDict]]
)


MessageContent = TypeAliasType("MessageContent", Union[str, List[ContentPartUnion]])
