"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sudo_ai.types import BaseModel
from typing_extensions import TypedDict


class ResponseEventTypedDict(TypedDict):
    pass


class ResponseEvent(BaseModel):
    pass
