"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import ConfigDict
from sudo_ai.types import BaseModel
from typing import Any, Dict
from typing_extensions import TypedDict


class ResponseEventDataTypedDict(TypedDict):
    r"""Server-sent event from the streaming Responses API. Contains dynamic fields based on event type (response.created, response.output_text.delta, etc.)"""

    type: str
    r"""The type of event (e.g., response.created, response.output_text.delta, response.done)"""
    sequence_number: int
    r"""Monotonically increasing sequence number for events in this response"""


class ResponseEventData(BaseModel):
    r"""Server-sent event from the streaming Responses API. Contains dynamic fields based on event type (response.created, response.output_text.delta, etc.)"""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: str
    r"""The type of event (e.g., response.created, response.output_text.delta, response.done)"""

    sequence_number: int
    r"""Monotonically increasing sequence number for events in this response"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class ResponseEventTypedDict(TypedDict):
    data: ResponseEventDataTypedDict
    r"""Server-sent event from the streaming Responses API. Contains dynamic fields based on event type (response.created, response.output_text.delta, etc.)"""


class ResponseEvent(BaseModel):
    data: ResponseEventData
    r"""Server-sent event from the streaming Responses API. Contains dynamic fields based on event type (response.created, response.output_text.delta, etc.)"""
