"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .supportedmodel import SupportedModel, SupportedModelTypedDict
from sudo_ai.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SupportedModelsListTypedDict(TypedDict):
    data: List[SupportedModelTypedDict]
    first_id: str
    has_more: bool
    last_id: str


class SupportedModelsList(BaseModel):
    data: List[SupportedModel]

    first_id: str

    has_more: bool

    last_id: str
