"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sudo_ai.types import BaseModel
from typing_extensions import TypedDict


class ToolCallFunctionTypedDict(TypedDict):
    arguments: str
    name: str


class ToolCallFunction(BaseModel):
    arguments: str

    name: str
