"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Any, List, Union
from typing_extensions import TypeAliasType


ToolCallOutputTypedDict = TypeAliasType(
    "ToolCallOutputTypedDict", Union[str, List[Any]]
)


ToolCallOutput = TypeAliasType("ToolCallOutput", Union[str, List[Any]])
