"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sudo_ai.types import BaseModel
from sudo_ai.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict
from typing_extensions import Annotated, TypedDict


class UpdateChatCompletionRequestBodyTypedDict(TypedDict):
    r"""Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters."""

    metadata: Dict[str, str]
    r"""The metadata key-value pairs to attach to the completion."""


class UpdateChatCompletionRequestBody(BaseModel):
    r"""Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters."""

    metadata: Dict[str, str]
    r"""The metadata key-value pairs to attach to the completion."""


class UpdateChatCompletionRequestTypedDict(TypedDict):
    completion_id: str
    r"""ID of the chat completion"""
    request_body: UpdateChatCompletionRequestBodyTypedDict
    r"""Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters."""


class UpdateChatCompletionRequest(BaseModel):
    completion_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the chat completion"""

    request_body: Annotated[
        UpdateChatCompletionRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters."""
