"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sudo_ai.types import BaseModel
from typing import Any, Optional
from typing_extensions import NotRequired, TypedDict


class UsageTypedDict(TypedDict):
    completion_tokens: int
    prompt_tokens: int
    total_tokens: int
    completion_tokens_details: NotRequired[Any]
    prompt_tokens_details: NotRequired[Any]


class Usage(BaseModel):
    completion_tokens: int

    prompt_tokens: int

    total_tokens: int

    completion_tokens_details: Optional[Any] = None

    prompt_tokens_details: Optional[Any] = None
